'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'..','browser','game.js'),'utf8');
const end=source.indexOf('const game=new NamakoApp();');
assert(end>0);
const elements=new Map();
const element=id=>{if(!elements.has(id))elements.set(id,{style:{},hidden:false,disabled:false,textContent:'',setAttribute(){},classList:{toggle(){}}});return elements.get(id);};
const sandbox={window:{},document:{getElementById:element},NamakoSession:{read:()=>null}};
vm.runInNewContext(source.slice(0,end)+'\nglobalThis.TestApp=NamakoApp;',sandbox);
const App=sandbox.TestApp;
function complete(demo){
 const app=Object.create(App.prototype);
 let grants=0,shown=0,trivia=0;
 app.mode='celebrate';app.rewardFromDemo=demo;app.roundId='round-1';
 app.audio={celebrate(){}};
 app.cards={rewardsEnabled:()=>true,milestoneUnlocked:()=>false,grantForRound(){grants++;return{id:'card-1'};},owned:()=>1};
 app.rewardView={show(){shown++;}};
 app.showTrivia=()=>{trivia++;};app.sync=()=>{};
 app.finishCelebration();
 return{grants,shown,trivia,mode:app.mode};
}
assert.deepEqual(complete(true),{grants:0,shown:0,trivia:1,mode:'celebrate'});
assert.deepEqual(complete(false),{grants:1,shown:1,trivia:0,mode:'reveal'});
const app=Object.create(App.prototype);
app.mode='demo';app.rewardFromDemo=false;app.collectionOpen=false;app.difficultyIndex=1;app.speedIndex=0;app.phase=0;app.demoClock=0;
app.audio={trackLabel:()=>'潮の庭',musicEnabled:true,sfxEnabled:true,play(){}};
app.cards={rewardsEnabled:()=>true,milestoneUnlocked:()=>false,ownedUnique:()=>0,enabledCards:()=>[{id:'card-1'}]};
app.model={fillRatio:()=>0,fillCount:()=>0,kept:0};app.celebrationMessage='';
app.rewardView={showCollection(){throw Error('demo opened collection');}};
app.sync();
assert.equal(element('cards-button').hidden,true);
app.openCollection();
assert.equal(app.collectionOpen,false);
app.mode='play';app.sync();
assert.equal(element('cards-button').hidden,false);
console.log('PASS demo cards: no grant, reveal, or collection in demo; normal play reward remains.');
