'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.join(__dirname,'..');
const source=JSON.parse(fs.readFileSync(path.join(root,'browser','lore_100_v2_1.json'),'utf8'));
assert.equal(source.version,'2.1');
assert.equal(source.entries.length,100);
assert.deepEqual(source.entries.map(entry=>entry.id),Array.from({length:100},(_,i)=>i+1));
assert.equal(new Set(source.entries.map(entry=>entry.title)).size,100);
assert.equal(new Set(source.entries.map(entry=>entry.body)).size,100);
assert(source.entries.every(entry=>entry.title&&entry.body.length>=140&&entry.body.length<=190));
const sandbox={window:{}};
vm.runInNewContext(fs.readFileSync(path.join(root,'browser','trivia_catalog.js'),'utf8'),sandbox);
const catalog=sandbox.window.NAMAKO_TRIVIA_CATALOG;
assert.equal(catalog.version,'2.1');
assert.equal(catalog.notice,source.notice);
assert.equal(JSON.stringify(catalog.episodes),JSON.stringify(source.entries));
const standalone=fs.readFileSync(path.join(root,'START.html'),'utf8');
const match=standalone.match(/<script>window\.NAMAKO_TRIVIA_CATALOG=(\{.*?\});<\/script>/s);
assert(match,'standalone lore catalog is embedded');
assert.equal(JSON.stringify(JSON.parse(match[1]).episodes),JSON.stringify(source.entries));
assert.match(standalone,/ツミナマコは架空の生き物です。/);
const Trivia=require('../browser/trivia.js');
const picker=new Trivia(catalog);
picker.lastId=0;
assert.equal(picker.pick(()=>0).id,1);
assert.notEqual(picker.pick(()=>0).id,1,'consecutive duplicate is skipped');
assert.equal(picker.byId(100).id,100);
console.log('PASS HTML lore v2.1: 100 unique long entries, split and standalone catalogs, no immediate repeat.');
