const fs=require('fs'),assert=require('assert'),{chromium}=require('playwright');
const root=require('path').resolve(__dirname,'..');
(async()=>{const browser=await chromium.launch(require('./browser_test_support').launchOptions);let checks=0;try{
for(const lang of ['ja','en'])for(const size of [[360,640],[390,844],[412,915],[1440,3200],[1280,800]])for(const dark of [false,true]){
 const page=await browser.newPage({viewport:{width:size[0],height:size[1]},deviceScaleFactor:2});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.setContent(fs.readFileSync(root+'/START.html','utf8').replace('<head>',`<head><script>window.NAMAKO_TEST_LANGUAGE='${lang}';window.NAMAKO_TEST_MODE=true;</script>`));await page.waitForFunction(()=>window.__namako);
 await page.evaluate(async dark=>{const g=__namako;g.dark=dark;g.applyTheme();g.beginPlay();for(let speed=0;speed<5;speed++){g.speedIndex=speed;for(let track=0;track<4;track++){g.audio.trackIndex=track;g.audio.musicEnabled=false;g.audio.sfxEnabled=false;g.sync();const buttons=['theme','track','speed','music','sfx','menu','lore-button','difficulty','cards-button'].map(id=>document.getElementById(id));for(const b of buttons){const st=getComputedStyle(b),c=document.createElement('canvas').getContext('2d');c.font=st.font;const w=c.measureText(b.textContent).width;if(w+4>b.clientWidth)throw Error('Text width '+b.id+' '+b.textContent+' '+w+'/'+b.clientWidth);}for(let i=1;i<5;i++){const a=buttons[i-1].getBoundingClientRect(),b=buttons[i].getBoundingClientRect();if(a.right>b.left+.5)throw Error('Settings overlap');}for(const b of buttons.slice(0,5)){const x=parseFloat(b.style.left),w=parseFloat(b.style.width);if(x<18||x+w>522)throw Error('Settings outside frame');}}}g.speedIndex=3;if(g.speed!==3)throw Error('3x');g.pause();if(g.mode!=='paused')throw Error('Pause');g.resume();const origin=g.origin.slice();g.openLore();if(g.mode!=='trivia')throw Error('Reader');g.moreLore();g.finishTrivia();if(g.mode!=='play'||String(g.origin)!==String(origin))throw Error('Restore');g.openLore();},dark);
 await page.waitForFunction(()=>getComputedStyle(document.getElementById('trivia')).opacity==='1');if(size[0]===390)await page.screenshot({path:root+`/tests/fullheight_browser_${lang}_${dark?'dark':'light'}_notes.png`});
 await page.evaluate(()=>{const paper=document.getElementById('trivia-paper'),g=__namako,panel=document.getElementById('trivia');if(Math.abs(parseFloat(panel.style.height)-(g.layoutHeight-32))>1)throw Error('Reader height');if(Math.abs(parseFloat(panel.style.top)-16)>1)throw Error('Reader top');const h=parseFloat(paper.style.height);if(h<300)throw Error('Paper too short');paper.scrollTop=10000;if(paper.scrollHeight>paper.clientHeight&&paper.scrollTop===0)throw Error('Cannot scroll');__namako.finishTrivia();});
 await page.waitForFunction(()=>getComputedStyle(document.getElementById('trivia')).opacity==='1');if(size[0]===390)await page.screenshot({path:root+`/tests/fullheight_browser_${lang}_${dark?'dark':'light'}_play.png`});
 await page.evaluate(async()=>{const g=__namako;g.mode='reveal';g.reduced=true;g.rewardView.show(g.cards.completionCard(),1,false);await document.getElementById('reward-front').decode();const p=document.getElementById('reward'),s=document.getElementById('reward-flip'),n=document.getElementById('reward-note'),b=document.getElementById('reward-next');if(Math.abs(parseFloat(p.style.height)-(g.layoutHeight-32))>0.1)throw Error('Reward height');if(parseFloat(s.style.height)<=420)throw Error('Card not enlarged');if(Math.abs(parseFloat(s.style.width)/parseFloat(s.style.height)-2/3)>.001)throw Error('Card aspect');if(parseFloat(s.style.top)+parseFloat(s.style.height)>parseFloat(n.style.top))throw Error('Card overlaps note');if(parseFloat(b.style.top)+b.offsetHeight>p.offsetHeight)throw Error('Reward button clipped');});
 await page.waitForFunction(()=>getComputedStyle(document.getElementById('trivia')).opacity==='1');if(size[0]===390)await page.screenshot({path:root+`/tests/fullheight_browser_${lang}_${dark?'dark':'light'}_reward.png`});
 assert.deepEqual(errors,[]);checks++;await page.close();
}console.log('PASS '+checks+' phone/desktop/language/theme cases: frame containment, full-height reader/reward, card aspect, labels, 3x, pause, resume, scroll');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});

