'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const manifest=JSON.parse(fs.readFileSync(path.join(__dirname,'../data/card_manifest.json'),'utf8'));
assert.equal(manifest.cards.length,20);
assert.deepEqual(manifest.ranks.map(r=>r.id),['N','R','SR','SSR','SECRET']);
assert.equal(manifest.rewards_enabled,true);
assert.equal(manifest.ranks.reduce((sum,r)=>sum+r.weight,0),100);
for(const card of manifest.cards){
 assert.equal(card.enabled,true);
 assert.equal(fs.existsSync(path.join(__dirname,'..',card.image)),true,card.id+' image missing');
 const header=fs.readFileSync(path.join(__dirname,'..',card.image)).subarray(0,12);
 assert.equal(header.toString('ascii',0,4),'RIFF');
 assert.equal(header.toString('ascii',8,12),'WEBP');
}
const saved=new Map();
const context={window:{NAMAKO_CARD_CATALOG:manifest},localStorage:{getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v)},module:{exports:{}}};
vm.createContext(context);
vm.runInContext(fs.readFileSync(path.join(__dirname,'../browser/cards.js'),'utf8'),context);
const Cards=context.module.exports;
const cards=new Cards(manifest);
assert.equal(cards.rewardsEnabled(),true);
assert.equal(cards.enabledCards().length,20);
assert.deepEqual([0,.60,.86,.97,.999].map(r=>cards.pickReward(()=>r).rank),['N','R','SR','SSR','SECRET']);
assert.equal(cards.ownedUnique(),0);
cards.add(manifest.cards[0]);
assert.equal(cards.owned('card_01'),1);
assert.equal(cards.pickReward(()=>0).id,'card_02','same-rank unseen card should be preferred');
for(const card of manifest.cards.slice(1,9))cards.add(card);
assert.equal(cards.ownedUnique(),9);
assert.equal(cards.milestoneUnlocked(),false);
cards.add(manifest.cards[9]);
assert.equal(cards.ownedUnique(),10);
assert.equal(cards.milestoneUnlocked(),true);
assert.equal(cards.totalOwned(),10);
const reloaded=new Cards(manifest);
assert.equal(reloaded.ownedUnique(),10,'collection should survive reload');
saved.set('namako_cards',JSON.stringify({__completionSeen:true,card_01:1}));
assert.equal(new Cards(manifest).completionSeen,false,'old twelve-card completion must reopen at twenty cards');
saved.set('namako_cards',JSON.stringify({__completionSeen:true,__completionSize:20,card_01:1}));
assert.equal(new Cards(manifest).completionSeen,true,'current twenty-card completion remains acknowledged');
console.log('PASS cards: 20 artwork files, five ranks, reward draw, unseen preference, saved collection and 10-card milestone.');
