'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const {chromium}=require('playwright');

(async()=>{
 const root=path.resolve(__dirname,'..');
 const edge='C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe';
 const browser=await chromium.launch({headless:true,executablePath:fs.existsSync(edge)?edge:undefined,args:['--autoplay-policy=no-user-gesture-required']});
 try{
  const page=await browser.newPage({viewport:{width:540,height:860}});
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(pathToFileURL(path.join(root,'START.html')).href+'?test=1',{waitUntil:'load'});
  await page.waitForFunction(()=>window.__namako&&window.__namako.cards.rewardsEnabled());
  assert.equal(await page.locator('#cards-button').innerText(),'図鑑 0/20');
  await page.click('#cards-button');
  assert.equal(await page.locator('#collection-grid .locked').count(),20);
  await page.click('#collection-close');
  await page.click('#theme');
  assert.equal(await page.evaluate(()=>__namako.dark),true);
  await page.waitForTimeout(6000);
  await page.screenshot({path:path.join(root,'tests','demo_dark_polish.png')});
  await page.reload({waitUntil:'load'});
  await page.waitForFunction(()=>window.__namako);
  assert.equal(await page.evaluate(()=>__namako.dark),true,'night mode persists');
  await page.click('#theme');
  await page.waitForTimeout(1500);
  await page.screenshot({path:path.join(root,'tests','demo_light_polish.png')});
  await page.click('#theme');
  await page.click('#start');
  await page.evaluate(()=>{
   const game=window.__namako;
   game.cards.pickReward=()=>game.cards.enabledCards().find(card=>card.id==='card_11');
   game.model.reset(123);
   let guard=0;
   while(!game.model.isClear()&&guard++<120){const spec=game.model.nextSpec(),plan=game.model.demoChoice(game.model.shape(spec.shape),false);game.model.commit(plan.cells,plan.origin,spec.color);}
   if(!game.model.isClear())throw new Error('test board did not clear');
   game.clear();game.finishCelebration();
  });
  assert.equal(await page.evaluate(()=>__namako.mode),'reveal');
  assert.equal(await page.locator('#reward').isVisible(),true);
  assert.match(await page.locator('#reward-note').innerText(),/SECRET キングナマコ/);
  assert.equal(await page.evaluate(()=>__namako.cards.owned('card_11')),1);
  assert.equal(await page.locator('#reward-front').evaluate(img=>img.complete&&img.naturalWidth>0),true);
  await page.evaluate(()=>{window.__played=[];__namako.audio.play=(name)=>window.__played.push(name);});
  await page.keyboard.press('r');
  assert.equal(await page.evaluate(()=>__namako.mode),'reveal','restart key cannot bypass reward');
  await page.waitForTimeout(2600);
  assert((await page.evaluate(()=>window.__played)).includes('card_rare'),'rare reveal plays new fanfare at face swap');
  assert.equal(await page.locator('#reward-front').isVisible(),true,'front must remain visible after spin');
  assert.equal(await page.locator('#reward-back').isVisible(),false,'back must disappear after spin');
  await page.screenshot({path:path.join(root,'tests','reward_secret_browser.png')});
  await page.click('#reward-next');
  assert.equal(await page.evaluate(()=>__namako.mode),'trivia');
  assert.equal(await page.locator('#trivia').isVisible(),true);
  assert.equal(await page.evaluate(()=>__namako.trivia.episodes.length),100);
  await page.click('#trivia-next');
  assert.equal(await page.evaluate(()=>__namako.mode),'play');
  await page.evaluate(()=>__namako.finishCelebration());
  assert.equal(await page.evaluate(()=>__namako.cards.owned('card_11')),1,'reward only once');
  await page.click('#cards-button');
  assert.equal(await page.locator('#collection-grid .owned').count(),1);
  assert.equal(await page.locator('#collection-grid .owned img').count(),1);
  await page.screenshot({path:path.join(root,'tests','collection_browser.png')});
  await page.click('#collection-close');
  await page.reload({waitUntil:'load'});
  await page.waitForFunction(()=>window.__namako);
  assert.equal(await page.evaluate(()=>__namako.cards.owned('card_11')),1,'collection persists across reload');
  await page.evaluate(()=>{for(const card of __namako.cards.enabledCards().slice(0,10))__namako.cards.add(card);__namako.sync();});
  assert.equal(await page.evaluate(()=>__namako.cards.milestoneUnlocked()),true);
  await page.setViewportSize({width:390,height:844});
  await page.click('#cards-button');
  const bounds=await page.locator('#collection-close').boundingBox();
  assert(bounds&&bounds.x>=0&&bounds.x+bounds.width<=390.5&&bounds.y+bounds.height<=844.5);
  assert.equal(await page.locator('body').innerText().then(text=>text.includes('家族')),false);
  await page.screenshot({path:path.join(root,'tests','mobile_dark_collection.png')});
  assert.deepEqual(errors,[]);
  console.log('PASS browser rewards: reveal, WebP image, one save, collection, reload, milestone and mobile access');
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
