'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),url=process.env.NAMAKO_TEST_URL||pathToFileURL(path.join(root,'artifacts/web/index.html')).href;
const original=fs.readFileSync(path.join(root,'assets/audio/professor_voice.wav'));
assert.deepEqual(fs.readFileSync(path.join(root,'artifacts/web/assets/audio/professor_voice.wav')),original);
const embedded=JSON.parse(fs.readFileSync(path.join(root,'START.html'),'utf8').match(/window\.NAMAKO_AUDIO=(\{.*?\});<\/script>/s)[1]);
assert.deepEqual(Buffer.from(embedded.professor_voice.split(',')[1],'base64'),original);
const wait=(page,fn)=>page.waitForFunction(fn,null,{polling:50,timeout:10000});
(async()=>{const browser=await chromium.launch(require('./browser_test_support').launchOptions);try{
 for(const language of ['ja','en']){
  const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:3,isMobile:true,hasTouch:true}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(language=>{window.NAMAKO_TEST_MODE=true;window.NAMAKO_TEST_LANGUAGE=language;window.requestAnimationFrame=()=>0;},language);
  await page.goto(url);await page.waitForFunction(()=>window.__namako);
  const musicLevel=await page.evaluate(()=>__namako.audio.music.volume);
  await page.locator('#lore-button').tap();await wait(page,()=>__namako.audio.voices.professor_voice[0].currentTime>.05);
  assert.equal(await page.evaluate(()=>__namako.mode),'trivia');
  assert(Math.abs(await page.evaluate(()=>__namako.audio.voices.professor_voice[0].duration)-3.253832199546485)<.001);
  assert(Math.abs(await page.evaluate(()=>__namako.audio.music.volume)-musicLevel*.3)<.0001,'BGM should be quieter during doctor voice');
  await page.locator('#trivia-more').tap();await page.evaluate(()=>__namako.toggleLanguage());
  assert.equal(await page.evaluate(()=>__namako.audio.voiceIndex.professor_voice),1,'next story/language must not repeat introduction');
  await wait(page,()=>__namako.audio.voices.professor_voice[0].ended&&!__namako.audio.narrationActive);
  assert(Math.abs(await page.evaluate(()=>__namako.audio.music.volume)-musicLevel)<.0001,'BGM should return to saved level');
  await page.locator('#trivia-next').tap();await page.locator('#lore-button').tap();await wait(page,()=>__namako.audio.voices.professor_voice[1].currentTime>.05);
  await page.locator('#trivia-next').tap();assert.equal(await page.evaluate(()=>__namako.audio.voices.professor_voice.every(a=>a.paused&&a.currentTime===0)&&!__namako.audio.narrationActive),true,'close must stop introduction');
  await page.evaluate(()=>__namako.audio.toggleSfx());await page.locator('#lore-button').tap();assert.equal(await page.evaluate(()=>__namako.audio.voicePlaying('professor_voice')||__namako.audio.narrationActive),false,'SFX OFF respected');await page.locator('#trivia-next').tap();
  await page.evaluate(()=>{const g=__namako;g.audio.toggleSfx();g.rewardFromDemo=true;g.showDemoTrivia();});await wait(page,()=>__namako.audio.voicePlaying('professor_voice'));
  assert.equal(await page.evaluate(()=>__namako.audio.voices.professor_voice.find(a=>!a.paused).volume),.55,'automatic demo narration softer');
  await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});
  assert.equal(await page.evaluate(()=>__namako.audio.voices.professor_voice.every(a=>a.paused)&&!__namako.audio.narrationActive&&__namako.audio.music.paused),true,'hidden tab stops narration');
  assert.deepEqual(errors,[]);assert.equal(await page.evaluate(()=>NamakoI18n.missing.size),0);await context.close();
 }
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),page=await context.newPage();
 await page.addInitScript(()=>{window.NAMAKO_TEST_MODE=true;window.requestAnimationFrame=()=>0;});await page.goto(url);await page.waitForFunction(()=>window.__namako);
 await page.evaluate(()=>{__namako.rewardFromDemo=true;__namako.showDemoTrivia();});assert.equal(await page.evaluate(()=>__namako.audio.voicePlaying('professor_voice')),false);
 await page.locator('#trivia-title').tap();await wait(page,()=>__namako.audio.voicePlaying('professor_voice'));
 assert.equal(await page.evaluate(()=>__namako.audio.voiceIndex.professor_voice),1,'first tap in automatic notes starts voice once');
 await page.evaluate(()=>window.dispatchEvent(new Event('pagehide')));assert.equal(await page.evaluate(()=>__namako.audio.voices.professor_voice.every(a=>a.paused)),true);
 await context.close();console.log('PASS doctor voice: original WAV in both builds, actual JA/EN notes-entry playback, once per visit, BGM duck/restore, no next-story/language repeat, SFX OFF, demo/tap fallback and exit/background cancellation.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
